export const SAVE_ACCOUNT = 'SAVE_ACCOUNT';
export const LOGIN = 'LOGIN';
export const REGISTER = 'REGISTER';

//
export const INDEX = 'INDEX';
export const LIST = 'LIST';
export const PLAYING = 'PLAYING';
export const EXPANDED = 'EXPANDED';
export const REPEAT = 'REPEAT';
export const SHUFFLE = 'SHUFFLE';
export const CURRENT_TIME = 'CURRENT_TIME';
export const TOTAL_TIME = 'TOTAL_TIME';
export const SHOW_PLAYER = 'SHOW_PLAYER';

//

export const FEATURED_TAB = 'FEATURED_TAB';
export const UPDATE_RECENTLY_PLAYED = 'UPDATE_RECENTLY_PLAYED';
export const UPDATE_FEATURED_ARTISTS = 'UPDATE_FEATURED_ARTISTS';

export const ARTISTS_TAB = 'ARTISTS_TAB';
export const UPDATE_UPCOMING_ARTISTS = 'UPDATE_UPCOMING_ARTISTS';
export const UPDATE_SUGGESTED_ARTISTS = 'UPDATE_SUGGESTED_ARTISTS';

export const ALBUMS_TAB = 'ALBUMS_TAB';
export const UPDATE_NEW_RELEASES = 'UPDATE_NEW_RELEASES';
export const UPDATE_PICKS = 'UPDATE_PICKS';
export const UPDATE_REGULARS = 'UPDATE_REGULARS';

export const PLAYLIST_TAB = 'PLAYLIST_TAB';

export const PLAYLIST = 'PLAYLIST';

export const UPDATE = 'UPDATE';

export const UPDATE_TAB_INDEX = 'UPDATE_TAB_INDEX';

export const UPDATE_IS_FINISHED = 'UPDATE_IS_FINISHED';

export const PLAYLIST_UPDATE_COUNTER = 'PLAYLIST_UPDATE_COUNTER';
export const UPDATE_UID = 'UPDATE_UID';
export const FLAG = 'FLAG';

//test
export const UPDATE_PLAYER_DATA = 'UPDATE_PLAYER_DATA';

export const UPDATE_COMMAND = 'UPDATE_COMMAND';

export const UPDATE_IDS = 'UPDATE_IDS';

export const UPDATE_AUTOPLAY = 'UPDATE_AUTOPLAY';

export const ADD_TO_DOWNLOAD_LIST = 'ADD_TO_DOWNLOAD_LIST';
export const REMOVE_FROM_DOWNLOAD_LIST = 'REMOVE_FROM_DOWNLOAD_LIST';
export const ADD_TO_SAVED_LIST = 'ADD_TO_SAVED_LIST';
export const REMOVE_FROM_SAVED_LIST = 'REMOVE_FROM_SAVED_LIST';
export const ADD_TO_DOWNLOAD_LIST_INFORMATION =
  'ADD_TO_DOWNLOAD_LIST_INFORMATION';

export const PREMIUM = 'PREMIUM';
export const OFFLINE = 'OFFLINE';
export const INIT_FINISHED = 'INIT_FINISHED';

export const DOWNLOADED_SONG_IDS = 'DOWNLOADED_SONG_IDS';
export const DOWNLOADING_SONG_IDS = 'DOWNLOADING_SONG_IDS';

export const DOWNLOADED_DATA = 'DOWNLOADED_DATA';
